

server:
  port : 5001
  #Data base connections
spring:
  datasource:
    name : restaurant
    url : jdbc:mysql://localhost:3306/digilocker
    username : admin1
    password : Test1234!%
  jpa:
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto : update
    show-sql : true

