server:
  port : 4502
  #Data base connections
spring:
  datasource:
    name : digilocker-database
    url : jdbc:mysql://localhost:3306/nirman_kyc
    username : admin
    password : Test1234!%
  jpa:
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto : update
    show-sql : true
